#!/usr/bin/env python3
"""
Personal Assistant Bot
Generated by Claude Code — you own every line.

Audit time : ~20 minutes
Lines      : ~280
Dependencies: anthropic, python-telegram-bot, python-dotenv
"""

import os
import subprocess
from pathlib import Path
from dotenv import load_dotenv
import anthropic
from telegram import Update
from telegram.ext import Application, MessageHandler, filters, ContextTypes

load_dotenv()

# ── Configuration ─────────────────────────────────────────────────────────────
TELEGRAM_TOKEN   = os.environ["TELEGRAM_TOKEN"]
ANTHROPIC_API_KEY = os.environ["ANTHROPIC_API_KEY"]
ALLOWED_USER_IDS  = {int(x.strip()) for x in os.environ["ALLOWED_USER_IDS"].split(",")}
WORKSPACE         = Path(os.environ.get("WORKSPACE", str(Path.home() / "assistant-workspace")))
MODEL             = os.environ.get("MODEL", "claude-sonnet-4-6")

# ── Security: what the assistant can and cannot touch ─────────────────────────
#
# These patterns are checked against every path component before any file
# operation. If a path contains any of these strings, the operation is
# rejected — even if the path resolves inside WORKSPACE.
#
BLOCKED_PATTERNS = {
    ".ssh", ".gnupg", ".aws", ".azure", ".gcloud", ".kube", ".docker",
    ".env", "credentials", ".netrc", ".npmrc",
    "id_rsa", "id_ed25519", "id_ecdsa", "private_key", ".secret",
}


def is_safe_path(path: str) -> bool:
    """True only if path resolves inside WORKSPACE and has no blocked components."""
    try:
        target = Path(path).resolve()
        if not str(target).startswith(str(WORKSPACE.resolve())):
            return False
        for part in target.parts:
            if any(blocked in part.lower() for blocked in BLOCKED_PATTERNS):
                return False
        return True
    except Exception:
        return False


# ── Tools (what Claude can call) ──────────────────────────────────────────────

def tool_read_file(path: str) -> str:
    if not is_safe_path(path):
        return f"Blocked: '{path}' is outside workspace or matches a blocked pattern."
    p = Path(path)
    if not p.exists():
        return f"Error: file not found: {path}"
    return p.read_text(encoding="utf-8", errors="replace")


def tool_write_file(path: str, content: str) -> str:
    if not is_safe_path(path):
        return f"Blocked: '{path}' is outside workspace or matches a blocked pattern."
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")
    return f"Written {len(content)} bytes to {p}"


def tool_shell(command: str) -> str:
    """Runs inside WORKSPACE only. 30-second timeout."""
    WORKSPACE.mkdir(parents=True, exist_ok=True)
    result = subprocess.run(
        command, shell=True, capture_output=True, text=True,
        cwd=str(WORKSPACE), timeout=30,
    )
    output = (result.stdout + result.stderr).strip()
    return output[:4000] if output else "(no output)"


def tool_list_dir(path: str = "") -> str:
    target = (WORKSPACE / path).resolve() if path else WORKSPACE.resolve()
    if not str(target).startswith(str(WORKSPACE.resolve())):
        return "Blocked: path is outside workspace."
    if not target.exists():
        return f"Error: directory not found: {target}"
    items = sorted(target.iterdir(), key=lambda p: (p.is_file(), p.name))
    lines = [f"{'[dir]  ' if p.is_dir() else '[file] '}{p.name}" for p in items]
    return "\n".join(lines) if lines else "(empty)"


# Tool schema — passed to Claude on every request
TOOL_DEFINITIONS = [
    {
        "name": "read_file",
        "description": "Read a file from the workspace directory.",
        "input_schema": {
            "type": "object",
            "properties": {
                "path": {"type": "string", "description": "Absolute or relative path (must be inside workspace)"},
            },
            "required": ["path"],
        },
    },
    {
        "name": "write_file",
        "description": "Write content to a file inside the workspace. Creates parent directories as needed.",
        "input_schema": {
            "type": "object",
            "properties": {
                "path":    {"type": "string", "description": "File path (must be inside workspace)"},
                "content": {"type": "string", "description": "File content"},
            },
            "required": ["path", "content"],
        },
    },
    {
        "name": "shell",
        "description": "Run a shell command inside the workspace directory. Max 30 seconds.",
        "input_schema": {
            "type": "object",
            "properties": {
                "command": {"type": "string", "description": "Shell command to run"},
            },
            "required": ["command"],
        },
    },
    {
        "name": "list_dir",
        "description": "List the contents of the workspace or a subdirectory.",
        "input_schema": {
            "type": "object",
            "properties": {
                "path": {"type": "string", "description": "Subdirectory path relative to workspace (optional)"},
            },
        },
    },
]

TOOL_DISPATCH = {
    "read_file": lambda inp: tool_read_file(inp["path"]),
    "write_file": lambda inp: tool_write_file(inp["path"], inp["content"]),
    "shell":      lambda inp: tool_shell(inp["command"]),
    "list_dir":   lambda inp: tool_list_dir(inp.get("path", "")),
}

# ── Anthropic agentic loop ─────────────────────────────────────────────────────

client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

# Per-user conversation history (in memory; resets on restart)
conversations: dict[int, list] = {}

SYSTEM_PROMPT = f"""You are a personal AI assistant accessible via Telegram.
Your workspace is: {WORKSPACE}

You can read files, write files, list directories, and run shell commands — \
but only inside the workspace directory. Never attempt to access paths outside it.

Keep responses concise and suitable for Telegram (under 4000 characters).
If a task will take multiple steps, describe what you're about to do first."""


def run_agent(user_id: int, user_message: str) -> str:
    history = conversations.setdefault(user_id, [])
    history.append({"role": "user", "content": user_message})

    # Keep last 20 messages to manage token cost
    if len(history) > 20:
        conversations[user_id] = history[-20:]
        history = conversations[user_id]

    while True:
        response = client.messages.create(
            model=MODEL,
            max_tokens=4096,
            system=SYSTEM_PROMPT,
            tools=TOOL_DEFINITIONS,
            messages=history,
        )

        history.append({"role": "assistant", "content": response.content})

        if response.stop_reason == "end_turn":
            text_blocks = [b.text for b in response.content if hasattr(b, "text")]
            return "\n".join(text_blocks) or "(no response)"

        if response.stop_reason == "tool_use":
            tool_results = []
            for block in response.content:
                if block.type == "tool_use":
                    fn = TOOL_DISPATCH.get(block.name)
                    result = fn(block.input) if fn else f"Unknown tool: {block.name}"
                    tool_results.append({
                        "type": "tool_result",
                        "tool_use_id": block.id,
                        "content": str(result),
                    })
            history.append({"role": "user", "content": tool_results})
        else:
            return f"(unexpected stop_reason: {response.stop_reason})"


# ── Telegram handler ───────────────────────────────────────────────────────────

async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    user_id = update.effective_user.id

    # Silently drop messages from anyone not in ALLOWED_USER_IDS.
    # No error message, no log — unauthorized callers get nothing.
    if user_id not in ALLOWED_USER_IDS:
        return

    text = (update.message.text or "").strip()
    if not text:
        return

    # Send a "thinking" placeholder while the agent loop runs
    thinking = await update.message.reply_text("…")

    try:
        reply = run_agent(user_id, text)
    except Exception as exc:
        reply = f"Error: {exc}"
    finally:
        await thinking.delete()

    # Telegram max message length is 4096 chars; chunk if needed
    for chunk_start in range(0, max(len(reply), 1), 4000):
        await update.message.reply_text(reply[chunk_start:chunk_start + 4000])


async def handle_reset(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Clear conversation history for this user (/reset command)."""
    user_id = update.effective_user.id
    if user_id not in ALLOWED_USER_IDS:
        return
    conversations.pop(user_id, None)
    await update.message.reply_text("Conversation cleared.")


# ── Entry point ────────────────────────────────────────────────────────────────

def main() -> None:
    from telegram.ext import CommandHandler

    WORKSPACE.mkdir(parents=True, exist_ok=True)
    print(f"Workspace : {WORKSPACE}")
    print(f"Authorized: {ALLOWED_USER_IDS}")
    print(f"Model     : {MODEL}")

    app = Application.builder().token(TELEGRAM_TOKEN).build()
    app.add_handler(CommandHandler("reset", handle_reset))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_message))

    print("Bot running. Press Ctrl+C to stop.")
    app.run_polling(drop_pending_updates=True)


if __name__ == "__main__":
    main()
