"""
test_security.py — Security test suite for bot.py
Generated by Claude Code via /test.

Run: pytest test_security.py -v

All tests should pass. A failing test means a security invariant is broken.
Do not disable or skip tests — fix the underlying issue in bot.py.
"""

import os
import pytest
from pathlib import Path
from unittest.mock import patch

# Patch required env vars before importing bot so it doesn't crash on startup
os.environ.setdefault("TELEGRAM_TOKEN", "test_token_not_real")
os.environ.setdefault("ANTHROPIC_API_KEY", "sk-ant-test_not_real")
os.environ.setdefault("ALLOWED_USER_IDS", "123456789")

import bot


# ── is_safe_path ──────────────────────────────────────────────────────────────

class TestIsSafePath:
    """is_safe_path() is the core security primitive. Every bypass here is a vulnerability."""

    def test_valid_path_inside_workspace(self, tmp_path):
        with patch.object(bot, "WORKSPACE", tmp_path):
            assert bot.is_safe_path(str(tmp_path / "notes.txt")) is True

    def test_valid_nested_path_inside_workspace(self, tmp_path):
        with patch.object(bot, "WORKSPACE", tmp_path):
            assert bot.is_safe_path(str(tmp_path / "projects" / "readme.md")) is True

    def test_blocks_absolute_path_outside_workspace(self, tmp_path):
        with patch.object(bot, "WORKSPACE", tmp_path):
            assert bot.is_safe_path("/etc/passwd") is False

    def test_blocks_path_traversal(self, tmp_path):
        with patch.object(bot, "WORKSPACE", tmp_path):
            assert bot.is_safe_path(str(tmp_path / ".." / "etc" / "passwd")) is False

    def test_blocks_double_traversal(self, tmp_path):
        with patch.object(bot, "WORKSPACE", tmp_path):
            assert bot.is_safe_path(str(tmp_path / "subdir" / ".." / ".." / "etc" / "passwd")) is False

    def test_blocks_ssh_directory(self, tmp_path):
        with patch.object(bot, "WORKSPACE", tmp_path):
            assert bot.is_safe_path(str(tmp_path / ".ssh" / "id_rsa")) is False

    def test_blocks_ssh_in_subdir(self, tmp_path):
        with patch.object(bot, "WORKSPACE", tmp_path):
            assert bot.is_safe_path(str(tmp_path / "backup" / ".ssh" / "config")) is False

    def test_blocks_aws_credentials(self, tmp_path):
        with patch.object(bot, "WORKSPACE", tmp_path):
            assert bot.is_safe_path(str(tmp_path / ".aws" / "credentials")) is False

    def test_blocks_gcloud(self, tmp_path):
        with patch.object(bot, "WORKSPACE", tmp_path):
            assert bot.is_safe_path(str(tmp_path / ".gcloud" / "token")) is False

    def test_blocks_kube_config(self, tmp_path):
        with patch.object(bot, "WORKSPACE", tmp_path):
            assert bot.is_safe_path(str(tmp_path / ".kube" / "config")) is False

    def test_blocks_docker_config(self, tmp_path):
        with patch.object(bot, "WORKSPACE", tmp_path):
            assert bot.is_safe_path(str(tmp_path / ".docker" / "config.json")) is False

    def test_blocks_env_file(self, tmp_path):
        with patch.object(bot, "WORKSPACE", tmp_path):
            assert bot.is_safe_path(str(tmp_path / ".env")) is False

    def test_blocks_dotenv_in_subdir(self, tmp_path):
        with patch.object(bot, "WORKSPACE", tmp_path):
            assert bot.is_safe_path(str(tmp_path / "config" / ".env")) is False

    def test_blocks_private_key(self, tmp_path):
        with patch.object(bot, "WORKSPACE", tmp_path):
            assert bot.is_safe_path(str(tmp_path / "private_key.pem")) is False

    def test_blocks_id_rsa(self, tmp_path):
        with patch.object(bot, "WORKSPACE", tmp_path):
            assert bot.is_safe_path(str(tmp_path / "id_rsa")) is False

    def test_blocks_id_ed25519(self, tmp_path):
        with patch.object(bot, "WORKSPACE", tmp_path):
            assert bot.is_safe_path(str(tmp_path / "id_ed25519")) is False

    def test_blocks_credentials_file(self, tmp_path):
        with patch.object(bot, "WORKSPACE", tmp_path):
            assert bot.is_safe_path(str(tmp_path / "credentials")) is False

    def test_blocks_npmrc(self, tmp_path):
        with patch.object(bot, "WORKSPACE", tmp_path):
            assert bot.is_safe_path(str(tmp_path / ".npmrc")) is False

    def test_blocks_netrc(self, tmp_path):
        with patch.object(bot, "WORKSPACE", tmp_path):
            assert bot.is_safe_path(str(tmp_path / ".netrc")) is False

    def test_blocks_secret_file(self, tmp_path):
        with patch.object(bot, "WORKSPACE", tmp_path):
            assert bot.is_safe_path(str(tmp_path / "api.secret")) is False

    def test_allows_txt_file(self, tmp_path):
        with patch.object(bot, "WORKSPACE", tmp_path):
            assert bot.is_safe_path(str(tmp_path / "notes.txt")) is True

    def test_allows_py_file(self, tmp_path):
        with patch.object(bot, "WORKSPACE", tmp_path):
            assert bot.is_safe_path(str(tmp_path / "script.py")) is True

    def test_allows_json_file(self, tmp_path):
        with patch.object(bot, "WORKSPACE", tmp_path):
            assert bot.is_safe_path(str(tmp_path / "data.json")) is True


# ── BLOCKED_PATTERNS completeness ─────────────────────────────────────────────

class TestBlockedPatternsCompleteness:
    """BLOCKED_PATTERNS must contain every required entry. Missing entries are vulnerabilities."""

    REQUIRED_PATTERNS = {
        ".ssh", ".gnupg", ".aws", ".azure", ".gcloud", ".kube", ".docker",
        ".env", "credentials", ".netrc", ".npmrc",
        "id_rsa", "id_ed25519", "private_key", ".secret",
    }

    def test_all_required_patterns_present(self):
        missing = self.REQUIRED_PATTERNS - bot.BLOCKED_PATTERNS
        assert not missing, (
            f"BLOCKED_PATTERNS is missing required entries: {missing}\n"
            f"These patterns protect against credential theft. Add them."
        )

    def test_blocked_patterns_is_a_set(self):
        assert isinstance(bot.BLOCKED_PATTERNS, (set, frozenset)), (
            "BLOCKED_PATTERNS should be a set for O(1) lookup, not a list."
        )


# ── tool_read_file ─────────────────────────────────────────────────────────────

class TestToolReadFile:
    """tool_read_file must reject unsafe paths before touching the filesystem."""

    def test_blocks_absolute_path_outside_workspace(self, tmp_path):
        with patch.object(bot, "WORKSPACE", tmp_path):
            result = bot.tool_read_file("/etc/passwd")
        assert "Blocked" in result

    def test_blocks_path_traversal(self, tmp_path):
        with patch.object(bot, "WORKSPACE", tmp_path):
            result = bot.tool_read_file(str(tmp_path / ".." / "secret"))
        assert "Blocked" in result

    def test_blocks_ssh_key(self, tmp_path):
        with patch.object(bot, "WORKSPACE", tmp_path):
            result = bot.tool_read_file(str(tmp_path / ".ssh" / "id_rsa"))
        assert "Blocked" in result

    def test_blocks_aws_credentials(self, tmp_path):
        with patch.object(bot, "WORKSPACE", tmp_path):
            result = bot.tool_read_file(str(tmp_path / ".aws" / "credentials"))
        assert "Blocked" in result

    def test_reads_valid_file(self, tmp_path):
        target = tmp_path / "hello.txt"
        target.write_text("hello world")
        with patch.object(bot, "WORKSPACE", tmp_path):
            result = bot.tool_read_file(str(target))
        assert result == "hello world"

    def test_returns_error_for_missing_file(self, tmp_path):
        with patch.object(bot, "WORKSPACE", tmp_path):
            result = bot.tool_read_file(str(tmp_path / "nonexistent.txt"))
        assert "error" in result.lower() or "not found" in result.lower()


# ── tool_write_file ────────────────────────────────────────────────────────────

class TestToolWriteFile:
    """tool_write_file must reject unsafe paths and only write inside the workspace."""

    def test_blocks_absolute_path_outside_workspace(self, tmp_path):
        with patch.object(bot, "WORKSPACE", tmp_path):
            result = bot.tool_write_file("/tmp/evil.txt", "payload")
        assert "Blocked" in result

    def test_blocks_path_traversal(self, tmp_path):
        with patch.object(bot, "WORKSPACE", tmp_path):
            result = bot.tool_write_file(str(tmp_path / ".." / "evil.txt"), "payload")
        assert "Blocked" in result

    def test_blocks_ssh_authorized_keys(self, tmp_path):
        with patch.object(bot, "WORKSPACE", tmp_path):
            result = bot.tool_write_file(str(tmp_path / ".ssh" / "authorized_keys"), "evil")
        assert "Blocked" in result

    def test_blocks_env_file(self, tmp_path):
        with patch.object(bot, "WORKSPACE", tmp_path):
            result = bot.tool_write_file(str(tmp_path / ".env"), "ANTHROPIC_API_KEY=stolen")
        assert "Blocked" in result

    def test_writes_valid_file(self, tmp_path):
        target = tmp_path / "output.txt"
        with patch.object(bot, "WORKSPACE", tmp_path):
            result = bot.tool_write_file(str(target), "content")
        assert target.read_text() == "content"
        assert "Written" in result

    def test_creates_parent_directories(self, tmp_path):
        target = tmp_path / "subdir" / "nested" / "file.txt"
        with patch.object(bot, "WORKSPACE", tmp_path):
            bot.tool_write_file(str(target), "nested content")
        assert target.read_text() == "nested content"


# ── tool_list_dir ──────────────────────────────────────────────────────────────

class TestToolListDir:
    """tool_list_dir must not expose directories outside the workspace."""

    def test_blocks_absolute_path_outside_workspace(self, tmp_path):
        with patch.object(bot, "WORKSPACE", tmp_path):
            result = bot.tool_list_dir("/etc")
        assert "Blocked" in result or "Error" in result

    def test_blocks_path_traversal(self, tmp_path):
        with patch.object(bot, "WORKSPACE", tmp_path):
            result = bot.tool_list_dir("../")
        assert "Blocked" in result or "Error" in result

    def test_lists_workspace_root(self, tmp_path):
        (tmp_path / "notes.txt").write_text("hi")
        (tmp_path / "subdir").mkdir()
        with patch.object(bot, "WORKSPACE", tmp_path):
            result = bot.tool_list_dir()
        assert "notes.txt" in result
        assert "subdir" in result

    def test_lists_subdirectory(self, tmp_path):
        subdir = tmp_path / "projects"
        subdir.mkdir()
        (subdir / "readme.md").write_text("hi")
        with patch.object(bot, "WORKSPACE", tmp_path):
            result = bot.tool_list_dir("projects")
        assert "readme.md" in result
